//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// EnvTool.rc에서 사용되고 있습니다.
//
#define IDD_DIALOG_FORM                 9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EnvToolTYPE                 130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDD_DIALOG1                     326
#define IDD_DIALOG2                     328
#define IDD_DIALOG3                     330
#define IDD_DIALOG4                     332
#define IDD_DIALOG5                     334
#define IDC_TAB1                        1006
#define IDC_EDIT_TERRAIN_SIZEX          1009
#define IDC_EDIT_TERRIAN_SIZEY          1010
#define IDC_BUTTON_ADJ_SIZE             1011
#define IDC_BUTTON_CAM_MAIN             1012
#define IDC_BUTTON_CAM_LIGHT            1013
#define IDC_EDIT1                       1014
#define IDC_EDIT_CAMSPEED               1014
#define IDC_EDIT_HEIGHTPOWER            1014
#define IDC_EDIT_MOUSE_POS_X            1014
#define IDC_EDIT2                       1015
#define IDC_EDIT_BRUSH_RANGE            1015
#define IDC_EDIT_MOUSE_POS_Y            1015
#define IDC_EDIT_POSX                   1015
#define IDC_BUTTON_ADJ_CAMSPEED         1016
#define IDC_EDIT8                       1016
#define IDC_EDIT_MOUSE_POS_Z            1016
#define IDC_EDIT_POSY                   1016
#define IDC_RADIO1                      1017
#define IDC_RADIO_UPTYPE_HEIGHT_1       1017
#define IDC_RADIO2                      1018
#define IDC_RADIO_UPTYPE_HEIGHT_2       1018
#define IDC_RADIO3                      1019
#define IDC_RADIO_UPTYPE_HEIGHT_3       1019
#define IDC_EDIT9_POSZ                  1019
#define IDC_EDIT_POSZ                   1019
#define IDC_SLIDER1                     1020
#define IDC_SLIDER_HEIGHTPOWER          1020
#define IDC_EDIT10                      1020
#define IDC_EDIT_DIR_POSX               1020
#define IDC_SLIDER2                     1021
#define IDC_SLIDER_RANGE                1021
#define IDC_SLIDER_DIR_POSX             1021
#define IDC_SLIDER3                     1022
#define IDC_SLIDER_DETAIL_DEFAULT       1022
#define IDC_SLIDER_DIR_POSY             1022
#define IDC_RADIO4                      1023
#define IDC_RADIO_HEIGHT_DIR_1          1023
#define IDC_SLIDER4                     1023
#define IDC_SLIDER_DIR_POSZ             1023
#define IDC_RADIO5                      1024
#define IDC_RADIO_HEIGHT_DIR_2          1024
#define IDC_SLIDER_POSX                 1024
#define IDC_BUTTON1                     1025
#define IDC_BUTTON_HEIGHT_RESET         1025
#define IDC_BUTTON_DELETE_OBJ           1025
#define IDC_BUTTON_NAVI_DELETE          1025
#define IDC_SLIDER_POSY                 1025
#define IDC_BUTTON_SKY_SAVE             1025
#define IDC_BUTTON2                     1026
#define IDC_BUTTON_DELETE_ALLOBJ        1026
#define IDC_SLIDER_POSZ                 1026
#define IDC_BUTTON_SKY_LOAD             1026
#define IDC_CHECK1                      1027
#define IDC_CHECK_COLLIDER              1027
#define IDC_CHECK_NAVI                  1027
#define IDC_CHECK_HEIGHT_INIT           1027
#define IDC_EDIT11                      1027
#define IDC_EDIT_DIR_POSY               1027
#define IDC_CHECK_COLLIDE_OBJ           1027
#define IDC_CHECK_HEIGHT                1028
#define IDC_BUTTON_NAVI_UNDO            1028
#define IDC_EDIT12                      1028
#define IDC_EDIT_DIR_POSZ               1028
#define IDC_RADIO_MODE_1                1029
#define IDC_RADIO_MODE_2                1030
#define IDC_RADIO_DETAIL_1              1031
#define IDC_RADIO_DETAIL_2              1032
#define IDC_RADIO_DETAIL_3              1033
#define IDC_RADIO_DETAIL_4              1034
#define IDC_RADIO_DETAIL_5              1035
#define IDC_EDIT3                       1036
#define IDC_EDIT4                       1037
#define IDC_EDIT5                       1038
#define IDC_EDIT6                       1039
#define IDC_EDIT7                       1040
#define IDC_BUTTON_TEX_LOAD             1041
#define IDC_EDIT13                      1041
#define IDC_EDIT_GLOBLIGHT_B            1041
#define IDC_BUTTON4                     1042
#define IDC_BUTTON_SPLAT_LOAD           1042
#define IDC_BUTTON_GLOBLIGHT_COLOR_ADJ  1042
#define IDC_BUTTON_RESET_SCALE          1042
#define IDC_BUTTON5                     1043
#define IDC_BUTTON_TERRAIN_SAVE         1043
#define IDC_BUTTON_GLOBLIGHT_RESET      1043
#define IDC_BUTTON_RESET_ROTATION       1043
#define IDC_BUTTON6                     1044
#define IDC_BUTTON_TERRAIN_LOAD         1044
#define IDC_BUTTON_RESET_POSITION       1044
#define IDC_SLIDER_SPLAT_POWER          1045
#define IDC_BUTTON8                     1045
#define IDC_BUTTON_POINT_SAVE           1045
#define IDC_BUTTON_RESET_ALL            1045
#define IDC_EDIT_SPLAT_POWER            1046
#define IDC_BUTTON14                    1046
#define IDC_EDIT_POINT_COLOR_ADJ        1046
#define IDC_LIST_OBJECTS                1047
#define IDC_EDIT16                      1047
#define IDC_EDIT_POINT_R                1047
#define IDC_LIST_OBJECT_TYPE            1048
#define IDC_EDIT17                      1048
#define IDC_EDIT_POINT_G                1048
#define IDC_EDIT18                      1049
#define IDC_EDIT_POINT_B                1049
#define IDC_BUTTON_OBJECT_SAVE          1050
#define IDC_BUTTON15                    1050
#define IDC_BUTTON_GLOBLIGHT_SAVE       1050
#define IDC_BUTTON_OBJECT_LOAD          1051
#define IDC_BUTTON_NAVI_SAVE            1052
#define IDC_BUTTON_OBJECT_LOAD_COLLIDE  1052
#define IDC_BUTTON_NAVI_LOAD            1053
#define IDC_BUTTON_OBJECT_SAVE_COLLIDE  1053
#define IDC_LIST_NAVI_POINT             1054
#define IDC_LIST_NAVI_CELL              1055
#define IDC_BUTTON_NAVI_CLEARALL        1056
#define IDC_BUTTON3                     1057
#define IDC_BUTTON_RESET_SELECTED       1057
#define IDC_BUTTON7                     1058
#define IDC_BUTTON_GLOBLIGHT_LOAD       1058
#define IDC_BUTTON9                     1059
#define IDC_BUTTON_POINT_LOAD           1059
#define IDC_LIST1                       1060
#define IDC_LIST_POINTLIGHT             1060
#define IDC_BUTTON10                    1061
#define IDC_BUTTON_POINT_LIST_SELDELETE 1061
#define IDC_BUTTON11                    1062
#define IDC_BUTTON_POINT_LIST_CLEARALL  1062
#define IDC_EDIT14                      1063
#define IDC_EDIT_POINT_RANGE            1063
#define IDC_EDIT_GLOBLIGHT_RANGE        1064
#define IDC_BUTTON12                    1065
#define IDC_BUTTON_POINT_RANGE_ADJ      1065
#define IDC_BUTTON_GLOBLIGHT_RANGE_ADJ  1066
#define IDC_EDIT_GLOBLIGHT_R            1068
#define IDC_EDIT_GLOBLIGHT_G            1069
#define IDC_COMBO_SKYTYPE               1070

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
